## Deep Learning

### Chapter 3: Working with Tensors



**Tensors** are fundamental data structures in deep learning, generalizations of vectors and matrices to an arbitrary number of dimensions (axes).

- A **1D tensor** is an array of numbers, representing a list of numerical data. It has one axis.
- A **2D tensor** is a matrix, an array of 1D tensors. It has two axes (rows and columns).
- A **3D tensor** is an array of 2D tensors, often used to represent images (height, width, color channels) or sequences of data.

This cell imports the necessary libraries:
- `numpy` (as `np`): A fundamental package for numerical computation in Python, especially for array operations.
- `tensorflow` (as `tf`): An open-source machine learning framework, crucial for creating and manipulating tensors.

In [18]:
import numpy as np
import tensorflow as tf

In [19]:
array1 = np.array([1, 2, 3, 4, 5])

tensor1 = tf.convert_to_tensor(array1)

print("1D Tensor")
print("Rank:", tensor1.ndim)
print("Shape:", tensor1.shape)

1D Tensor
Rank: 1
Shape: (5,)


In [20]:
array2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

tensor2 = tf.convert_to_tensor(array2)

print("2D Tensor")
print("Rank:", tensor2.ndim)
print("Shape:", tensor2.shape)

2D Tensor
Rank: 2
Shape: (3, 4)


In [21]:
array3 = np.array([
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],

    [
        [7, 8],
        [9, 10],
        [11, 12]
    ]
])

tensor3 = tf.convert_to_tensor(array3)

print("3D Tensor")
print("Rank:", tensor3.ndim)
print("Shape:", tensor3.shape)

3D Tensor
Rank: 3
Shape: (2, 3, 2)


**Common Tensor Operations**

This cell performs **element-wise arithmetic operations** on two TensorFlow constant tensors, `a` and `b`.
- `a + b`: Adds corresponding elements of `a` and `b`.
- `a - b`: Subtracts corresponding elements of `b` from `a`.
- `a * b`: Multiplies corresponding elements of `a` and `b`.

In [22]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


**Tensor Multiplication**
- Tensors can be multiplied using the `tf.matmul` function, which performs matrix multiplication. This is different from element-wise multiplication and is essential for operations in neural networks.

In [23]:
x = tf.constant([[1, 2]])
w = tf.constant([[3], [4]])

result = tf.matmul(x, w)

print(result)

tf.Tensor([[11]], shape=(1, 1), dtype=int32)


**Tensor Slicing**


- `array[1, 2]` accesses the element at the second row (index 1) and third column (index 2) of `array`.

In [24]:
print(array2[1, 2])

70



- `array[0]` retrieves the entire first row (index 0) of the 2D array.

In [25]:
print(array2[0])

[10 20 30 40]



- `array[:, 1]` retrieves all rows (`:`) but only the second column (index 1), effectively extracting the entire second column.

In [26]:
print(array2[:, 1])

[ 20  60 100]


In [27]:
print(array3[0])

[[1 2]
 [3 4]
 [5 6]]


`tf.reduce_mean(tensor2)` computes the average of all numerical values present in the 2D tensor.

In [28]:
print(tf.reduce_mean(tensor2))

tf.Tensor(65, shape=(), dtype=int64)


`tf.reduce_mean(tensor2, axis=0)` computes the average of elements down each column, resulting in a 1D tensor where each element is the mean of its respective column.

In [29]:
print(tf.reduce_mean(tensor2, axis=0))

tf.Tensor([50 60 70 80], shape=(4,), dtype=int64)


- `tf.reduce_mean(tensor2, axis=1)` computes the average of elements across each row, resulting in a 1D tensor where each element is the mean of its respective row.

In [30]:
print(tf.reduce_mean(tensor2, axis=1))

tf.Tensor([ 25  65 105], shape=(3,), dtype=int64)


- `tf.reduce_min(tensor2)` returns the smallest value in the tensor.
- `tf.reduce_max(tensor2)` returns the largest value in the tensor.

In [31]:
print(tf.reduce_min(tensor2))
print(tf.reduce_max(tensor2))

tf.Tensor(10, shape=(), dtype=int64)
tf.Tensor(120, shape=(), dtype=int64)


**Tensor Operations on MNIST**

In [32]:
# Load the MNIST dataset
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Show the rank, shape and dtype
print("Rank:", train_images.ndim)
print("Shape:", train_images.shape)
print("Data Type:", train_images.dtype)

Rank: 3
Shape: (60000, 28, 28)
Data Type: uint8


In [33]:
digit = train_images[0]
print(digit.shape)

(28, 28)



- `train_images[0, 10:20, 10:20]` extracts a 10x10 pixel sub-region from the first image. This showcases how to select specific parts of a multi-dimensional array or tensor.

In [34]:
my_slice = train_images[0, 10:20, 10:20]

print(my_slice.shape)

(10, 10)
